steps:
# Call docker build to build the image, using the previous build for caching
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'pull', 'gcr.io/$PROJECT_ID/prometheus-kubernetes/reposync:latest' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
    '--cache-from', 'gcr.io/$PROJECT_ID/prometheus-kubernetes/reposync:latest',
    '-t', 'gcr.io/$PROJECT_ID/prometheus-kubernetes/reposync:$COMMIT_SHA', '.']
  dir: 'reposync'
# Tag the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/prometheus-kubernetes/reposync:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/prometheus-kubernetes/reposync:latest']
# Push the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/prometheus-kubernetes/reposync:$COMMIT_SHA']
# Remote tag the newly pushed image as latest
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['container', 'images', 'add-tag', 'gcr.io/$PROJECT_ID/prometheus-kubernetes/reposync:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/prometheus-kubernetes/reposync:latest']
# Fetch the secrets repo
- name: 'gcr.io/$PROJECT_ID/keybase-builder:latest'
  args: ["keybase oneshot -u $_KEYBASE_USER -paperkey '$_KEYBASE_PAPERKEY' && git clone -b $_KEYBASE_BRANCH $_KEYBASE_REPO_URL secrets-repo"]
# Update k8s secrets: reposync
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - --namespace=reposync
  - delete
  - secret
  - prometheus-reposync
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=$_CLOUDSDK_COMPUTE_ZONE'
  - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLOUDSDK_CONTAINER_CLUSTER'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - --namespace=reposync
  - create
  - secret
  - generic
  - prometheus-reposync
  - --from-file=google.json=secrets-repo/kubernetes/reposync_service_acc.json
  - --from-file=github_id_rsa=secrets-repo/others/github_id_rsa_prometheus
  - --from-file=github_id_rsa.pub=secrets-repo/others/github_id_rsa_prometheus.pub
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=$_CLOUDSDK_COMPUTE_ZONE'
  - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLOUDSDK_CONTAINER_CLUSTER'
# Update the reposync deployment to use the image we just built
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - --namespace=reposync
  - set
  - image
  - deployment
  - reposync-prometheus-kubernetes
  - reposync=gcr.io/$PROJECT_ID/prometheus-kubernetes/reposync:$COMMIT_SHA
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=$_CLOUDSDK_COMPUTE_ZONE'
  - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLOUDSDK_CONTAINER_CLUSTER'