apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
  - port: 443
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana